language: ruby
cache: bundler

rvm:
  - ruby
  - 2.0.0-p353

script: 'bundle exec rake test:run_test'

notifications:
  email:
    recipients:
      - my@email.com
    on_failure: change
    on_success: never